---
hetzner_autosetup_file: autosetup
hetzner_disk1: sda
hetzner_disk2: sdb
hetzner_image: "/root/.oldroot/nfs/install/../images/CentOS-76-64-minimal.tar.gz"
hetzner_image_ignore_errors: false
# hetzner_webservice_username: 
# hetzner_webservice_password:
# hetzner_hostname: "hostname.example.com"

