apiVersion: v1 
kind: ConfigMap 
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring 
data:
  config.yaml: | 
    prometheusK8s:
      retention: 24h 
      volumeClaimTemplate:
        metadata:
          name: ocs-prometheus-claim
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd 
          resources:
            requests:
              storage: 20Gi
    alertmanagerMain: 
      volumeClaimTemplate:
        metadata:
          name: ocs-alertmanager-claim
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd 
          resources:
            requests:
              storage: 20Gi